version: "3.8"

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      # Add other environment variables as needed
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: ecommerce-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
